import React from 'react';

export default () => (
  <svg version="1.1" id="radar-circle-other" pointerEvents="none">
    <circle
      cx="50%"
      cy="50%"
      r="0"
      fillOpacity="0"
      stroke="white"
      strokeWidth="16px"
      strokeOpacity="0.4"
    >
      <animate
        attributeName="r"
        from="0"
        to="1220"
        dur="6s"
        repeatCount="indefinite"
        begin="0.25s"
      />
    </circle>

    <circle
      cx="50%"
      cy="50%"
      r="0"
      fillOpacity="0"
      stroke="white"
      strokeWidth="12px"
      strokeOpacity="0.4"
    >
      <animate
        attributeName="r"
        from="0"
        to="1220"
        dur="6s"
        repeatCount="indefinite"
        begin="1.25s"
      />
    </circle>

    <circle
      cx="50%"
      cy="50%"
      r="0"
      fillOpacity="0"
      stroke="white"
      strokeWidth="8px"
      strokeOpacity="0.4"
    >
      <animate
        attributeName="r"
        from="0"
        to="1220"
        dur="6s"
        repeatCount="indefinite"
        begin="2.25s"
      />
    </circle>

    <circle
      cx="50%"
      cy="50%"
      r="0"
      fillOpacity="0"
      stroke="white"
      strokeWidth="4px"
      strokeOpacity="0.4"
    >
      <animate
        attributeName="r"
        from="0"
        to="1220"
        dur="6s"
        repeatCount="indefinite"
        begin="3.25s"
      />
    </circle>

    <circle
      cx="50%"
      cy="50%"
      r="0"
      fillOpacity="0"
      stroke="white"
      strokeWidth="2px"
      strokeOpacity="0.4"
    >
      <animate
        attributeName="r"
        from="0"
        to="1220"
        dur="6s"
        repeatCount="indefinite"
        begin="4.25s"
      />
    </circle>
  </svg>
);
